### ISSUE TITLE
Internal Server Error on Login - Setup Issues?

### ISSUE THREAD

**Issue by pjeffries74** [oktadev/okta-wordpress-sign-in-widget#25]
Hello, I think I'm missing a step. 
When I attempt to authenticate using Okta, I am receiving an internal error message from the Okta login box.  I also cannot login as a local wp user.  So for now I have deactivated the app.
I may have setup wrong.  May I ask you a couple of questions?   
1) I had the original okta plugin installed and activated on Wordpress.  Once I download your widget app, should I deactivate the original okta plugin?
2) I'm not sure what you mean by setting up a "service" app for the second set of ClientID and Secret.   I setup two OpenID apps, one was the SPA where I gave it the ClientID.   The second app, I setup an OpenID Web Application.  I made sure to use the same login uri's as the first app.  Then used it's ClientID and Client Secret in the widget settings.
I checked the checkbox for allow local users to login, but when I go to the admin site and use the local admin account, it gives me the okta error again.  
Please help!  I apologize for my lack of knowledge with Okta.

**Comment by aaronpk** [comment]
You should have only one version of this plugin installed, I have no idea what will happen if two are installed but I'm sure it won't be good.

I just pushed a change to remove the extra client ID/secret so you only need one now.

If you still get errors can you provide the error message?

**Comment by pjeffries74** [comment]
Thank you for the reply!  I have deleted the older app.  It's giving me the same error (I'll paste it below).  When you say, "Register a "Service" app in Okta and provide its Client ID."  What exactly does this mean?  Sorry for the noob type of question :)

There was an unexpected internal error. Please try again."
"
![error](https://user-images.githubusercontent.com/68025323/86958915-ec920080-c12a-11ea-831e-93b1dcaa39b5.PNG)

**Comment by aaronpk** [comment]
Thanks! Can you open the developer console of the browser and paste a screenshot? That should have a more helpful error message.

(btw if you update to the latest code you don't need to register a service app anymore)

**Comment by pjeffries74** [comment]
Thanks, I updated to the latest code and using it now.  I am attaching the screenshot with the developer tools opened
Thank you for your help!
![dev](https://user-images.githubusercontent.com/68025323/86971990-28839080-c140-11ea-9856-3be5acf2f4cd.PNG)

**Comment by pjeffries74** [comment]
As a note, we are using the WPS Hide Login URL.  That is the URL I put in for the Login redirect URIs.  Would this have anything to do with it?

**Comment by aaronpk** [comment]
oh gosh, I have no idea how this plugin is going to interact with that plugin. Is the okta widget appearing on your new hidden login URL?

Can you view source of this web page and paste everything between the `<script>` tags? I want to see what wordpress is setting in the Okta config on this page.

**Comment by pjeffries74** [comment]
Thank you!
<script src="https://global.oktacdn.com/okta-signin-widget/4.1.3/js/okta-sign-in.min.js" type="text/javascript"></script>
<link href="https://global.oktacdn.com/okta-signin-widget/4.1.3/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>

<style type="text/css">
    #wordpress-login{
        text-align: center;
    }

    #wordpress-login a{
        font-size:10px;
        color: #999;
        text-decoration:none;
        font-family: montserrat,Arial,Helvetica,sans-serif;
    }
</style>

<div id="primary" class="content-area">
  <div id="widget-container"></div>
        <div id="wordpress-login"><a href="http://s33645.p1256.sites.pressdns.com/unl0ck/?wordpress_login=true">Login via Wordpress</a></div>
  </div>

<script>
    var signIn = new OktaSignIn({
        baseUrl: 'https://kemi.okta.com/',
        redirectUri: 'http://s33645.p1256.sites.pressdns.com/unl0ck/',
        el: '#widget-container',
        authParams: {
            display: 'page',
            issuer: 'https://kemi.okta.com/'
        }
    });
    if(signIn.hasTokensInUrl()) {
        if(document.getElementById('wordpress-login')) {
            document.getElementById('wordpress-login').remove();
        }
        // Grab the auth code from the URL and exchange it for an ID token
        signIn.authClient.token.parseFromUrl()
            .then(function (res) {
                signIn.authClient.tokenManager.add('id_token', res.tokens.idToken);
                // Redirect back to this page with the ID token in the URL. The backend will validate it and log the user in.
                window.location = 'http://s33645.p1256.sites.pressdns.com/unl0ck/?log_in_from_id_token='+res.tokens.idToken.value;
            });
    }
    else {
        signIn.showSignInToGetTokens({
            clientId: '0oaerjccqieLO6VQ71t7',
            getAccessToken: false,
            getIdToken: true,
            scope: 'openid email'
        });
    }
</script>

**Comment by pjeffries74** [comment]
Just in case the above paste is not readable. 
[html.txt](https://github.com/oktadeveloper/okta-wordpress-sign-in-widget/files/4896560/html.txt)

**Comment by aaronpk** [comment]
Okay great, and you said the custom login URL is the one you put in Okta as the login redirect URL? Can you verify that in the application settings in Okta? 

Can you verify that the domain `s33645.p1256.sites.pressdns.com` is listed under "Trusted Origins"? You can find that in the admin UI under Security -> API -> Trusted Origins, or in the developer console under API -> Trusted Origins.
