### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by jonascencio** [oktadev/okta-wordpress-sign-in-widget#31]
I have set my Okta settings correctly, URI's and Trusted Origins are set. Once logging into through Okta successfully, it sends me back to the login screen which creates just a loop of logging in but with no direct access to the Wordpress Console. I can verify that logs show a success within all attempts both application, user, and Console logs.
<img width="970" alt="Screen Shot 2020-10-14 at 5 40 44 PM" src="https://user-images.githubusercontent.com/64100363/96061120-3fc0d100-0e47-11eb-8766-39f7326e3ea8.png">

**Comment by aaronpk** [comment]
Do you see anything in the browser console on the redirect? I just tested this again with a stock wordpress install and an okta developer account and it worked fine.
